version: '3.9'

services:
    placerem:
        build: 
            context: .
        command: >
            sh -c   "
                    npm run dev &&
                    python manage.py wait_for_db &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000
                    "
        volumes: 
            - ./placerem:/placerem
            - ./data/web:/vol/web
            # If you want to prevent copying node_modules files to container
            # /placerem/node_modules/
        ports: 
            - 8000:8000
        env_file: .env
        depends_on: 
            - db

    db:
        image: postgres:13-alpine
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
