version: '3.9'

services:
    placerem:
        build: 
            context: .
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        ports: 
            - 8000:8000
        volumes: 
            - ./placerem:/placerem
            - ./data/web:/vol/web
        environment: 
            - SECRET_KEY=devsecretkey12345
            - DEBUG=1
            - SOCIAL_AUTH_VK_OAUTH2_KEY=7913462
            - SOCIAL_AUTH_VK_OAUTH2_SECRET=N450JZ5X4bWdM9cW9AWC
            - SOCIAL_AUTH_GITHUB_KEY=36401c899e91f10a256b
            - SOCIAL_AUTH_GITHUB_SECRET=6163b8d049781a0a80696146c84a278f179f22d8
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASS=devpassword
        depends_on: 
            - db

    db:
        image: postgres:13-alpine
        environment: 
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=devpassword
