# Generated by Django 3.2.5 on 2021-07-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published in')),
                ('location', models.CharField(max_length=40, verbose_name='Location')),
                ('destination', models.CharField(max_length=40, verbose_name='Destination')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recollection',
                'verbose_name_plural': 'Recollections',
                'ordering': ['-published'],
            },
        ),
    ]
