# Generated by Django 3.2.5 on 2021-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_recollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recollection',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='Destination'),
        ),
    ]
