# Generated by Django 3.2.5 on 2021-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_recollection_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recollection',
            name='destination',
            field=models.CharField(max_length=100, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='recollection',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='recollection',
            name='location',
            field=models.CharField(max_length=40, null=True, verbose_name='Location'),
        ),
    ]
