# Generated by Django 3.2.5 on 2021-07-12 15:31

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20210711_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recollection',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='recollection',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='recollection',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='recollection',
            name='geometry',
            field=djgeojson.fields.PointField(null=True),
        ),
    ]
