# Generated by Django 3.2.5 on 2021-07-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_auto_20210712_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recollection',
            old_name='geometry',
            new_name='geom',
        ),
    ]
