# Generated by Django 3.2.5 on 2021-08-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20210730_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recollection',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
