# Generated by Django 3.2.6 on 2021-08-04 06:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_recollection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
