# Generated by Django 3.2.6 on 2021-08-18 09:58

import django.core.validators
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, error_messages={'invalid_extension': 'This format does not supported'}, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png'))], verbose_name='Photo'),
        ),
    ]
