# Generated by Django 3.2.6 on 2021-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Username'),
        ),
    ]
